### ISSUE TITLE
close function not working

### ISSUE THREAD

**Issue by alanzou** [aws-samples/amazon-lex-v2-lambdahook-for-booktripbot#1]
there is a bug in close function

def close(session_attributes, active_contexts, fulfillment_state, intent, message):
    response = {
        'sessionState': {
            'activeContexts':[{
                'name': 'intentContext',
                'contextAttributes': active_contexts,
                'timeToLive': {
                    'timeToLiveInSeconds': 600,
                    'turnsToLive': 1
                }
            }],
            'sessionAttributes': session_attributes,
            'dialogAction': {
                'type': 'Close',
            },
            'intent': intent
        },
         'messages': [message]
    }

    return response

**Comment by sita158** [comment]
Hi Alanzou, 
At this point I am eliminating the "messages" attribute from the returning JSON in all functions, since it is optional, and this code is being reused in a tailored workshop that does not require it. I will be working on a version that contains the attribute and will work with the standard Lex Book Trip Blueprint.
Thank you...
